### ISSUE TITLE
Missing snippet: Export interface

### ISSUE THREAD

**Issue by tnotheis** [DevExpress/vscode-rushsnippets#2]
I would love to have a snippet `xi` for exporting an interface.

**Comment by eugeneryabinin** [comment]
> I would love to have a snippet `xi` for exporting an interface.

Hi,

Thank you for sharing this idea.
We've added this snippet. It will be available in our next update.

**Comment by eugenr79** [comment]
Hi,

We released an update containing a new "xi" snippet.

**Comment by eugeneryabinin** [comment]
Hi,

We released an update containing a new "xi" snippet.
